init commit
clowder-framework/jclowder pull request #1
Opened 2021-01-27 18:12 UTC by bingzhang

2021-02-04 21:01 UTC, robkooper requested changes

2021-02-04 21:01 UTC, robkooper commented on src/main/java/edu/illinois/ncsa/clowder/extractor/Extractor.java
> +public abstract class Extractor {
can you add some javadoc, especially to this class.

2021-02-04 21:01 UTC, robkooper commented on src/main/java/edu/illinois/ncsa/clowder/extractor/ExtractorException.java
> +public class ExtractorException extends Exception {
In DataWolf we have an AbortException as well, that is an extension of the base ExtractorException. This would then indicate that we have an error that would never get resolved.

2021-02-04 21:01 UTC, robkooper commented on src/main/java/edu/illinois/ncsa/clowder/extractor/ExtractorRunner.java
> +    try {
can you use a formatter to make sure it is formatted consistently

2021-02-04 22:14 UTC, bingzhang commented on src/main/java/edu/illinois/ncsa/clowder/extractor/Extractor.java
> +public abstract class Extractor {
done.

2021-02-04 22:26 UTC, bingzhang commented on src/main/java/edu/illinois/ncsa/clowder/extractor/ExtractorException.java
> +public class ExtractorException extends Exception {
May you share the code link of AbortException in DataWolf?

2021-02-04 22:27 UTC, bingzhang commented on src/main/java/edu/illinois/ncsa/clowder/extractor/ExtractorException.java
> +public class ExtractorException extends Exception {
I can refer to that implementation.

2021-02-17 17:23 UTC, bingzhang commented on src/main/java/edu/illinois/ncsa/clowder/extractor/ExtractorException.java
> +public class ExtractorException extends Exception {
> In DataWolf we have an AbortException as well, that is an extension of the base ExtractorException. This would then indicate that we have an error that would never get resolved.

I checked the reference link you suggested. The code is almost the same.

2021-03-17 15:27 UTC, max-zilla commented
I was able to build and run this with a newer JDK by adding these lines to pom.xml:

```	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
```

Specifically the two maven.compiler lines. After I did that, I was able to run the wordcount java version on my local Clowder and successfully got it done, and also it threw errors on deleted files without a big issues which is good. Do you want to add those 2 lines to the pom file and I will approve?

2021-03-17 15:27 UTC, max-zilla requested changes
it will not build with newer JDK (I have 14) without two additions to properties XML file.

2021-03-17 16:10 UTC, bingzhang commented
> I was able to build and run this with a newer JDK by adding these lines to pom.xml:
> 
> ```
> 		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
> 		<maven.compiler.source>1.8</maven.compiler.source>
> 		<maven.compiler.target>1.8</maven.compiler.target>
> 	</properties>
> ```
> 
> Specifically the two maven.compiler lines. After I did that, I was able to run the wordcount java version on my local Clowder and successfully got it done, and also it threw errors on deleted files without a big issues which is good. Do you want to add those 2 lines to the pom file and I will approve?

thank you. I updated the pom.xml.

2021-03-17 16:12 UTC, max-zilla approved these changes

2021-03-17 16:12 UTC, max-zilla commented
@robkooper i'm good to merge if you are.

2021-03-17 19:45 UTC, robkooper requested changes

2021-03-17 19:45 UTC, robkooper commented on pom.xml
> +		<!--<dependency>-->
just remove if not needed

2021-03-17 19:45 UTC, robkooper commented on pom.xml
> +		<dependency>
can we make sure we have the latest version (for example 5.11 is out for rabbitmq).

2021-03-17 19:45 UTC, robkooper commented on pom.xml
> +		<url>https://opensource.ncsa.illinois.edu/bitbucket/scm/cats/jclowder.git</url>
this should point to github

2021-03-17 19:45 UTC, robkooper commented on src/main/java/example/WordCount.java
> +    System.out.println("userParam: " + userParam);
please use loggers

2021-03-17 19:45 UTC, robkooper commented on src/main/resources/extractor_info.json
> +{
can this be formatted (for example use jq).

2021-03-17 19:45 UTC, robkooper commented on src/main/resources/extractor_info.json
> +"author": "Rob Kooper <kooper@illinois.edu>",
I'm not the author

2021-03-17 19:45 UTC, robkooper commented on src/main/resources/extractor_info.json
> +}
can you add the catalog option for type as well.

2021-03-17 19:45 UTC, robkooper commented on src/main/java/example/WordCount.java
> +      ex.printStackTrace();
use logger.exception for this

2021-03-17 19:45 UTC, robkooper commented on src/main/java/example/WordCount.java
> +    content.put("characters", (Integer)count);
either return lines/words/characters or change the description in extractor_info.json

2021-03-17 19:45 UTC, robkooper commented on pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
can you consistent format this file (same indentation).

2021-03-23 21:46 UTC, bingzhang commented on pom.xml
> +		<!--<dependency>-->
removed.

2021-03-23 21:47 UTC, bingzhang commented on pom.xml
> +		<dependency>
done.

2021-03-23 21:48 UTC, bingzhang commented on pom.xml
> +		<url>https://opensource.ncsa.illinois.edu/bitbucket/scm/cats/jclowder.git</url>
done.

2021-03-23 21:51 UTC, bingzhang commented on src/main/java/example/WordCount.java
> +    System.out.println("userParam: " + userParam);
done.

2021-03-23 21:52 UTC, bingzhang commented on src/main/resources/extractor_info.json
> +"author": "Rob Kooper <kooper@illinois.edu>",
put me on it.

2021-03-23 21:53 UTC, bingzhang commented on src/main/resources/extractor_info.json
> +{
done.

2021-03-23 21:55 UTC, bingzhang commented on src/main/resources/extractor_info.json
> +}
I am not sure what is the format of catalog option. Is it '"catalog": []'?

2021-03-23 21:58 UTC, bingzhang commented on src/main/java/example/WordCount.java
> +      ex.printStackTrace();
done.

2021-03-23 21:59 UTC, bingzhang commented on src/main/java/example/WordCount.java
> +    content.put("characters", (Integer)count);
done.

2021-03-23 22:11 UTC, bingzhang commented on pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
done.

2021-03-23 22:12 UTC, bingzhang commented on pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
done.

2021-03-24 02:24 UTC, robkooper commented on src/main/resources/extractor_info.json
> +"bibtex": []
```suggestion
"bibtex": [],
  "labels": [
    "Type/Audio"
  ]
```

2021-03-24 02:24 UTC, robkooper commented on src/main/resources/extractor_info.json
> +}
see above

2021-03-24 02:28 UTC, robkooper approved these changes

2021-03-24 14:24 UTC, merged